#pragma once

// Generated by tools/generate_certs.sh for kitchen node
// Replace with actual certificate data

// Root CA Certificate (shared across all nodes)
extern const uint8_t ca_pem_start[] asm("_binary_ca_pem_start");
extern const uint8_t ca_pem_end[] asm("_binary_ca_pem_end");

// Kitchen Node Client Certificate  
extern const uint8_t client_pem_start[] asm("_binary_kitchen_pem_start");
extern const uint8_t client_pem_end[] asm("_binary_kitchen_pem_end");

// Kitchen Node Private Key
extern const uint8_t client_key_start[] asm("_binary_kitchen_key_start");
extern const uint8_t client_key_end[] asm("_binary_kitchen_key_end");

// Certificate validation
#define CA_CERT_CN "HomeVoice Root CA"
#define CLIENT_CERT_CN "kitchen"
#define SERVER_CERT_CN "assistant.lan"

// Certificate sizes (approximate)
#define CA_CERT_SIZE 1300
#define CLIENT_CERT_SIZE 1000  
#define CLIENT_KEY_SIZE 1000 