/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * QUAL-29: the per-language phrasing for a handler donation. Joined to the language-neutral contract.json by method_name#intent_suffix and param name. Carries phrases/lemmas/patterns/examples + per-param description/extraction_patterns/aliases/default_value/choice_surfaces. NO ParameterSpec core (that lives once in contract.json).
 */
export interface IreneIntentDonationPerLanguagePhrasingV11 {
  $schema?: string;
  schema_version: "1.1";
  handler_domain?: string;
  language: string;
  description?: string;
  stop_command_patterns?: string[];
  action_patterns?: string[];
  additional_recognition_patterns?: string[];
  negative_patterns?: unknown[];
  language_detection?: {};
  train_keywords?: string[];
  method_donations: Method[];
  global_parameters?: Param[];
  [k: string]: unknown;
}
export interface Method {
  method_name: string;
  intent_suffix: string;
  description?: string;
  phrases?: string[];
  lemmas?: string[];
  token_patterns?: unknown[];
  slot_patterns?: {};
  examples?: {}[];
  parameters?: Param[];
}
export interface Param {
  name: string;
  description?: string;
  extraction_patterns?: {}[];
  aliases?: string[];
  default_value?: unknown;
  /**
   * {canonical token: [spoken surface forms in this language]}
   */
  choice_surfaces?: {
    [k: string]: string[];
  };
}
